//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public string PartsName { get; set; }
        public Nullable<int> ModelsId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
